/* tslint:disable */
/* eslint-disable */
/**
 * Personas APIs Definition
 * # About Us **Persona Builder** Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
 *
 * OpenAPI spec version: 0.0.1
 * Contact: support@personas.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Persona
 */
export interface Persona {
    /**
     * 
     * @type {number}
     * @memberof Persona
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Persona
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Persona
     */
    type?: PersonaTypeEnum;
    /**
     * 
     * @type {Date}
     * @memberof Persona
     */
    createdAt?: Date;
    /**
     * 
     * @type {any}
     * @memberof Persona
     */
    attributes?: any;
    /**
     * 
     * @type {any}
     * @memberof Persona
     */
    conditions?: any;
}

/**
    * @export
    * @enum {string}
    */
export enum PersonaTypeEnum {
    Default = 'default',
    Predefined = 'predefined'
}

